### ISSUE TITLE
Display local images

### ISSUE THREAD

**Issue by trozware** [objecthub/swift-markdownkit#1]
Great package and really useful, but I was wondering is there a way to display local images?

Setting up an image with a web URL works perfectly, but using a local URL, even if I start it with `file://` does not translate to an image block.

**Comment by objecthub** [comment]
I wasn't able to reproduce this issue. I have included some image tests here:
https://github.com/objecthub/swift-markdownkit/blob/master/Tests/MarkdownKitTests/MarkdownHtmlTests.swift

Can you send me some Markdown text with an image link included that shows the issue you found?
Thanks!

**Comment by trozware** [comment]
You are correct. MarkdownKit is producing the correct HTML for local images.
WKWebView refuses to display them and I was confusing the two issues.
Sorry for the confusion and thanks again for the great library.
