### ISSUE TITLE
Html inside of code blocks gets rendered as html

### ISSUE THREAD

**Issue by Jomy10** [objecthub/swift-markdownkit#10]
## Problem
Using the HTMLGenerator, if there is html inside of code blocks, it will be rendered as html instead of as text. This causes undefined behaviour.

**Example**: here, a css stylesheet is being rendered, messing up the webpage. (see highlighted line)
![Schermafbeelding 2022-02-04 om 02 12 28](https://user-images.githubusercontent.com/62475953/152456036-5ad15c9d-b2f2-4e04-9476-eadec2b4e3d7.png)

## Proposed solution
Replace all `<` with `&lt;` inside of code blocks and `>` with `&gt;`.

**Comment by objecthub** [comment]
Thanks a lot for the bug report! I just submitted a fix for this problem. Release 1.1.3 shouldn't have this problem anymore.
