### ISSUE TITLE
Inline highlighting without a split pane?

### ISSUE THREAD

**Issue by erikvlm** [objecthub/swift-markdownkit#11]
Is it possible to create only a single window where a user types in markdown and have it dynamically rendered? Sort of like Obsidian / Bear app / Spaces does it?

Eg writing `**bold**` to only show **bold**? (Notice that the asterisks have been "hidden") - all in one window, without having a "preview" and an "editor" mode so to say

**Comment by objecthub** [comment]
This framework is parsing and transforming Markdown. It does not come with a specific display logic. This is functionality that is orthogonal to the framework.
