### ISSUE TITLE
Linux compatibility?

### ISSUE THREAD

**Issue by kevinrenskers** [objecthub/swift-markdownkit#3]
The core parser and HTML renderer seem to just rely on Foundation, so they should run on Linux as well. Yet because of the AttributedString renderer the supported platforms are limited to `.macOS(.v10_12)` and `.iOS(.v12)`. Could this possibly be split up into a separate package? Or maybe there is another way to achieve the same result, namely that this package can be used in pure Swift libraries that run on CI.

**Comment by kevinrenskers** [comment]
I think I misunderstood the meaning of those platform values, this shouldn't stop Linux support. However, the `AttributedString` related code should probably be wrapped with `#if !os(Linux)` and `#endif`?

**Comment by objecthub** [comment]
I've added Linux compatibility to the project. I only checked that the command-line tool is compiling and the tests are all passing.
