### ISSUE TITLE
Example of creating a simple inline parser?

### ISSUE THREAD

**Issue by kevinrenskers** [objecthub/swift-markdownkit#5]
Let's say I want to add support for `~~strikethrough~~` text, and I want to write a plugin for that. How would I go about doing this? I found https://github.com/objecthub/swift-markdownkit/blob/master/Sources/MarkdownKit/Parser/EmphasisTransformer.swift but this seems quite complex for something that feels should be rather simple 🤔  Is there no helper function available that takes a "delimiter" like `**` or `~~` and transforms the text in between them?

**Comment by objecthub** [comment]
Agreed that this was overkill. I made MarkdownKit extensible and also provided a simple way to implement emphasis delimiters. Instructions are in the README file.
